name: cas
version: "7.2.0"
description: "Claude Agent System - Parallel agent swarms for planning, implementation, and code review"
author: "Kasempiternal"
repository: "https://github.com/Kasempiternal/Claude-Agent-System"
